apimServiceName: cc-apiops-test
loggers:
- name: appInsights
  properties:
    resourceId: /subscriptions/e1f57a36-4892-4716-9a3f-661432b39dbe/resourceGroups/CC-APIOPS-TEST/providers/microsoft.insights/components/cc-apiops-test-ai
namedValues:
- name: AppInsightsKey
  properties:
    displayName: AppInsightsKey
    keyVault:
      secretIdentifier: https://cc-apiops-test-kv.vault.azure.net/secrets/AppInsightsKey
