openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: 2024-07-12a
servers:
  - url: https://cc-apiops-apim.azure-api.net/starwars/2024-07-12a
paths:
  /characters:
    get:
      summary: Get Characters
      description: Get Characters
      operationId: get-characters
      responses:
        '200':
          description: ''
  '/characters/{id}':
    get:
      summary: Get Character
      description: Get Charactter
      operationId: get-charactter
      parameters:
        - name: id
          in: path
          description: Character identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]